name: publish

on:
  push:
    branches:
      - feat/docker

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build katydid-service image
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u code-sherpas --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}